#!/usr/bin/env bash

# Requirements that this installer will not install by design
which sec || exit 1
which openssl || exit 1

echo
echo "Press the return key to install, or control+c to abort install script."
read resume

chmod +x badger-chainz
cp badger-chainz /usr/local/sbin/

chmod +x access-cleaner
cp access-cleaner /usr/local/sbin/

mkdir -p /opt/badger-chainz/workspace/
mkdir -p /opt/badger-chainz/etc/
cp chainz.cfg /opt/badger-chainz/etc/

cd /opt/badger-chainz/
openssl genrsa 4096 > secret-rsa.pem
openssl ecparam -name secp384r1 -genkey -noout -out secp384r1.pem
openssl ec -in secp384r1.pem -pubout -out secp384r1.pub
cp secp384r1.pem chain.key

# more to come here...
