#!/usr/bin/env bash

# Requirements that this installer will not install by design
which sec || exit 1
which openssl || exit 1
which gpg || exit 1

echo
echo "Press the return key to install, or control+c to abort install script."
read resume


# I have gotten NGINX to work with the FIFO, but not in all situations!
rm -f /var/log/nginx/access.log
mkfifo /var/log/nginx/access.log
chown www-data:root /var/log/nginx/access.log # found this helped here

# tests are failing for restarting httpd with FIFO in place! Account for that, yikes!
rm -f /var/log/httpd/access._log
mkfifo /var/log/httpd/access_log

# tests are failing for restarting apache2 with FIFO in place! Account for that, yikes!
rm -f /var/log/apache2/access._log
mkfifo /var/log/apache2/access_log


chmod +x badger-weblog
cp badger-weblog /usr/local/sbin/badger-chainz

mkdir -p /opt/badger-chainz/workspace/
mkdir -p /opt/badger-chainz/etc/
cp weblog.cfg /opt/badger-chainz/etc/

cd /opt/badger-chainz/


# more to come here...
