#!/usr/bin/env bash

# Requirements that this installer will not install by design
which sec || exit 1
which openssl || exit 1
which gpg || exit 1

echo
echo "Press the return key to install, or control+c to abort install script."
read resume

chmod +x badger-weblog
cp badger-weblog /usr/local/sbin/badger-chainz

mkdir -p /opt/badger-chainz/workspace/
mkdir -p /opt/badger-chainz/etc/
cp weblog.cfg /opt/badger-chainz/etc/

cd /opt/badger-chainz/


# more to come here...
